# This is a basic workflow to help you get started with Actions

name: Publish example site

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          ref: publish
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
    
      - name: Merge main -> publish
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: publish
          github_token: ${{ github.token }}
          
      - name: Change directory
        run: cd exampleSite
      
      - name: Build
        run: hugo --minify

      - name: Run a multi-line script
        run: |
          cd ../
          rm -rf docs/
          cp -r exampleSite/public docs  
